accounts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = 'accounts'
urlpatterns = [
    # path('', TemplateView.as_view(template_name='main/welcome.html'), name='home'),
    path('', UserLoginView.as_view(), name='index'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('home/', UserDashboardView.as_view(), name='dashboard'),
    path('addstaff/', AddStaffView.as_view(), name='add-staff'),
    path('viewstaff/', ListStaffView.as_view(), name='view-staff'),
    path('updatestaff/<int:pk>/', StaffUpdateView.as_view(), name='update-staff'),
    path('deletestaff/<int:pk>/', delete_staff, name='delete-staff'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('changepassword/', UserPasswordChangeView.as_view(), name='password_change'),
    path('passwordchanged/', UserPasswordChangeDoneView.as_view(), name='password_changed'),
    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(), name='activate'),
    path('profile/<int:pk>', ProfileEditView.as_view(), name='profile'),
    path('profile-info/<int:pk>', ProfileInfo.as_view(), name='profile-info'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cases/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = 'cases'

urlpatterns = [
    path('addcase/', AddCaseView.as_view(), name='add-case'),
    path('downloadcase/<int:pk>', download_case, name='download-case'),
    path('approvecase/<int:pk>', approve_view, name='approve-case'),
    path('listcases/', ListCaseView.as_view(), name='list-case'),
    path('wanted-list/', WantedCaseView.as_view(), name='wanted-list'),
    path('missing-list/', MissingCaseView.as_view(), name='missing-list'),
    path('found-list/', FoundCaseView.as_view(), name='found-list'),
    path('editcase/<int:pk>', UpdateCaseView.as_view(), name='edit-case'),
    path('deletecase/<pk>', delete_case, name='delete-case'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

detection/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = 'detection'
urlpatterns = [
    path('detectimage/', detect_image, name='detect-image'),
    path('detectwithvideo/', detect_video, name='detect-video'),
    path('detectwithwebcam/', detect_with_webcam, name='detect-webcam'),
    path('adduser/', add_staff, name='add-user'),
    path('addcitizen/', AddCitizen.as_view(), name='add-citizen'),
    path('viewcitizen/', ListCitizenView.as_view(), name='view-citizen'),
    path('deletecitizen/<int:pk>/', delete_citizen, name='delete-citizen'),
    path('updatecitizen/<int:pk>/', UpdateCitizenView.as_view(), name='update-citizen'),
    path('downloadcsvfile/<int:pk>/', csv_database_write, name='download-csv-file'),
    path('spottedcitizen/', SpottedCitizenView.as_view(), name='spotted-citizen'),
    path('citizenlocation/<int:pk>', citizen_location, name='citizen-location'),
    path('foundcitizen/<int:pk>/', found_citizen, name='found-citizen'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = 'news'
urlpatterns = [
    path('news/', NewsView.as_view(), name='list-news'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python_FaceRecognition/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('detection.urls')),
    path('', include('cases.urls')),
    path('', include('news.urls')),
    path('', include('searching.urls')),
    path('', include('feedback.urls')),

]

cases/models.py
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User

GENDER_CHOICES = (
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Other', 'Other'),
)

STATUS_CHOICES = (
    ('Wanted', 'Wanted'),
    ('Spotted', 'Spotted'),
    ('Missing', 'Missing'),
    ('Found', 'Found'),
)


class CaseQueryset(models.QuerySet):
    def search(self, query=None):
        qs = self
        if query is not None:
            or_lookup = (Q(case_first_name__icontains=query) | Q(case_last_name__icontains=query)
                         | Q(address__iexact=query)
                         | Q(status__iexact=query) | Q(gender__iexact=query))
            qs = qs.filter(or_lookup).distinct()
        return qs


class CaseManager(models.Manager):
    def get_queryset(self):
        return CaseQueryset(self.model, using=self._db)

    def search(self, query=None):
        return self.get_queryset().search(query=query)


class CasesModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=100, blank=False, null=True)
    case_first_name = models.CharField(max_length=50, blank=False, null=True)
    case_last_name = models.CharField(max_length=50, blank=False, null=True)
    case_location = models.CharField(max_length=50, blank=False, null=True)
    date_of_case = models.DateTimeField(blank=False, null=True)
    image = models.ImageField(blank=False, null=False, upload_to='cases/')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, blank=False, null=False)
    case_description = models.TextField(max_length=500, blank=True, null=True)

    reporter_first_name = models.CharField(max_length=50, blank=True, null=True)
    reporter_last_name = models.CharField(max_length=50, blank=True, null=True)
    address = models.CharField(max_length=100, blank=True, null=True)
    contact_email = models.EmailField(max_length=100, blank=True, null=True)
    contact_number = models.CharField(max_length=14, blank=True, null=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, blank=True, null=True)
    reporter_description = models.TextField(max_length=500, blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['-updated_at']

    def __str__(self):
        return self.title

    objects = CaseManager()

cases/forms.py
import re
from django import forms
from PIL import Image
from .models import *


class CaseForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height = forms.FloatField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = CasesModel
        fields = '__all__'
        exclude = ['user']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'case_first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'case_last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'case_location': forms.TextInput(attrs={'class': 'form-control'}),
            'date_of_case': forms.DateInput(attrs={'class': 'datepicker form-control', 'type': 'date'}),
            'case_description': forms.Textarea(attrs={'class': 'form-control'}),

            'reporter_first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'reporter_last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'contact_email': forms.EmailInput(attrs={'class': 'form-control'}),
            'contact_number': forms.TextInput(attrs={'class': 'form-control'}),
            'reporter_description': forms.Textarea(attrs={'class': 'form-control'}),
        }

    def clean_contact_number(self):
        contact_number = self.cleaned_data.get('contact_number')
        CONTACT_NUMBER_REGEX = re.compile(r"^(([+]?\d{3})-?)?\d{7,10}$")
        if not CONTACT_NUMBER_REGEX.match(contact_number):
            raise forms.ValidationError('''Phone Number format is not valid. Some examples of supported
              phone numbers are numbers are 9811111111, 08256666,
              977-9833333333, +977-9833333333, 977-08256666''')
        return contact_number

    def save(self, commit=True):
        photo = super(CaseForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        p_image = Image.open(photo.image)
        if x and y and w and h:
            cropped_image = p_image.crop((x, y, w + x, h + y))
            resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
            resized_image.save(photo.image.path)
        return photo

cases/views.py
import csv
from django.db import transaction
from django.shortcuts import render
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from .forms import CaseForm, CasesModel
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from url_encryption import *


@method_decorator(login_required, name='dispatch')
class AddCaseView(CreateView):
    template_name = 'cases/add_cases.html'
    form_class = CaseForm
    success_url = reverse_lazy('accounts:dashboard')

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        if not request.user.is_authenticated:
            messages.warning(request, 'Please login first')
            return redirect('accounts:login')
        else:
            return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)

        if form.is_valid():
            usercase = form.save(commit=False)
            usercase.user = self.request.user
            usercase.save()
            messages.success(request, 'Case added successfully')
            return redirect('accounts:dashboard')

        # messages.error(request, 'Please check your credentials again')
        print(form.errors)
        return render(request, self.template_name, {'form': form})


@login_required
def download_case(request, pk):
    try:
        case = CasesModel.objects.get(pk=pk)
    except CasesModel.DoesNotExist:
        messages.error(request, "Case not found")
        return redirect('cases:list-case')

    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="Details.csv"'

    writer = csv.writer(response)
    writer.writerow(['first_name', 'last_name', 'address', 'nationality', 'contact_number', 'email',
                     'gender', 'date_of_case', 'status', 'description'])

    writer.writerow([case.first_name, case.last_name, case.address, case.contact_number,
                     case.nationality, case.description,
                     case.image, case.status])
    return response


@login_required
def approve_view(request, pk):
    approve = CasesModel.objects.get(pk=pk)
    approve.is_approved = not approve.is_approved
    approve.save()
    return redirect('cases:list-case')


@method_decorator(login_required, name='dispatch')
class ListCaseView(ListView):
    template_name = 'cases/list_cases.html'
    model = CasesModel
    context_object_name = 'cases'
    paginate_by = 4


@method_decorator(login_required, name='dispatch')
class WantedCaseView(ListView):
    template_name = 'cases/list-wanted.html'
    model = CasesModel
    context_object_name = 'cases'


@method_decorator(login_required, name='dispatch')
class MissingCaseView(ListView):
    template_name = 'cases/list-missing.html'
    model = CasesModel
    context_object_name = 'cases'


@method_decorator(login_required, name='dispatch')
class FoundCaseView(ListView):
    template_name = 'cases/list-found.html'
    model = CasesModel
    context_object_name = 'cases'


@login_required
def delete_case(request, pk):
    try:
        case = CasesModel.objects.get(pk=pk)
    except CasesModel.DoesNotExist:
        messages.error(request, "Case not found")
        return redirect('cases:list-case')
    case.delete()
    messages.success(request, "Case deleted successfully")
    return redirect('cases:list-case')


@method_decorator(login_required, name='dispatch')
class UpdateCaseView(UpdateView):
    model = CasesModel
    form_class = CaseForm
    template_name = 'cases/update_cases.html'
    context_object_name = 'case'

    def form_valid(self, form):
        case = form.save(commit=False)
        case.updated_by = self.request.user
        case.updated_at = timezone.now()
        case.save()
        return redirect('cases:list-case')

cases/templates/cases/add_cases.html
{% extends 'base.html' %}

{% block javascripts %}
    <script>
        $(function () {

            /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
            $("#id_image").change(function () {
                if (this.files && this.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        $("#image").attr("src", e.target.result);
                        $("#modalCrop").modal("show");
                    }
                    reader.readAsDataURL(this.files[0]);
                }
            });

            /* SCRIPTS TO HANDLE THE CROPPER BOX */
            var $image = $("#image");
            var cropBoxData;
            var canvasData;
            $("#modalCrop").on("shown.bs.modal", function () {
                $image.cropper({
                    viewMode: 1,
                    aspectRatio: 1/1,
                    minCropBoxWidth: 200,
                    minCropBoxHeight: 200,
                    ready: function () {
                        $image.cropper("setCanvasData", canvasData);
                        $image.cropper("setCropBoxData", cropBoxData);
                    }
                });
            }).on("hidden.bs.modal", function () {
                cropBoxData = $image.cropper("getCropBoxData");
                canvasData = $image.cropper("getCanvasData");
                $image.cropper("destroy");
            });

            $(".js-zoom-in").click(function () {
                $image.cropper("zoom", 0.1);
            });

            $(".js-zoom-out").click(function () {
                $image.cropper("zoom", -0.1);
            });

            /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
            $(".js-crop-and-upload").click(function () {
                var cropData = $image.cropper("getData");
                $("#id_x").val(cropData["x"]);
                $("#id_y").val(cropData["y"]);
                $("#id_height").val(cropData["height"]);
                $("#id_width").val(cropData["width"]);
                {#$("#formUpload").submit();#}
            });

        });
    </script>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">
                        <h3 class="title">Add Case<a href="{% url 'accounts:dashboard' %}" style="float: right;display: block"><i class="tim-icons icon-simple-remove"></i></a>
                        </h3>
                    </div>
                    <div class="card-header">
                        <h5 class="title">Case Details</h5>
                    </div>
                    <div class="card-body">
                        <form method="post"  enctype="multipart/form-data" id="formUpload">
                            {% csrf_token %}

                            {{ form.x }}
                            {{ form.y }}
                            {{ form.width }}
                            {{ form.height }}

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Case Title</label>
                                        {{ form.title }}
                                        <span class="text-danger">{{ form.title.errors }}</span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6 pr-md-1">
                                    <div class="form-group">
                                        <label>First Name</label>
                                        {{ form.case_first_name }}
                                        <span class="text-danger">{{ form.case_first_name.errors }}</span>
                                    </div>
                                </div>
                                <div class="col-md-6 pl-md-1">
                                    <div class="form-group">
                                        <label>Last Name</label>
                                        {{ form.case_last_name }}
                                        <span class="text-danger">{{ form.case_last_name.errors }}</span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6 pr-md-1">
                                    <div class="form-group">
                                        <label>Case Location</label>
                                        {{ form.case_location }}
                                        <span class="text-danger">{{ form.case_location.errors }}</span>
                                    </div>
                                </div>
                                <div class="col-md-6 pl-md-1">
                                    <div class="form-group">
                                        <label>Date of Case</label>
                                        {{ form.date_of_case }}
                                        <span class="text-danger">{{ form.date_of_case.errors }}</span>
                                    </div>
                                </div>
                            </div>


                            <div class="row">
                                <div class="col-md-4 pr-md-1">
                                    <div class="form-group">
                                        <label>Status</label><br>
                                        {{ form.status }}
                                        <span class="text-danger">{{ form.status.errors }}</span>
                                    </div>
                                </div>

                                <div class="col-md-4 pr-md-1">
                                    <div class="img-holder">
                                        <label>Upload Evidence (image/video)</label><br>
                                        {{ form.image }}
                                        <span class="text-danger">{{ form.image.errors }}</span>
                                    </div>
                                </div>
                            </div><br>

                            <div class="row">
                                <div class="col-md-8">
                                    <div class="form-group">
                                        <label>Description</label>
                                        {{ form.case_description }}
                                        <span class="text-danger">{{ form.case_description.errors }}</span>
                                    </div>
                                </div>
                            </div>

                            {% if user.is_staff or user.is_superuser %}
                                <hr	style="border-top: 3px double #8c8b8b;">

                                <div>
                                    <h5 class="title">Reporter's Details</h5>
                                </div>
                                <div class="row">
                                    <div class="col-md-6 pr-md-1">
                                        <div class="form-group">
                                            <label>First Name</label>
                                            {{ form.reporter_first_name }}
                                            <span class="text-danger">{{ form.reporter_first_name.errors }}</span>
                                        </div>
                                    </div>
                                    <div class="col-md-6 pl-md-1">
                                        <div class="form-group">
                                            <label>Last Name</label>
                                            {{ form.reporter_last_name }}
                                            <span class="text-danger">{{ form.reporter.last_name.errors }}</span>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6 pr-md-1">
                                        <div class="form-group">
                                            <label>Address</label>
                                            {{ form.address }}
                                            <span class="text-danger">{{ form.address.errors }}</span>
                                        </div>
                                    </div>
                                    <div class="col-md-6 pl-md-1">
                                        <div class="form-group">
                                            <label>Phone Number</label>
                                            {{ form.contact_number }}
                                            <span class="text-danger">{{ form.contact_number.errors }}</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6 pr-md-1">
                                        <div class="form-group">
                                            <label>Email</label>
                                            {{ form.contact_email }}
                                            <span class="text-danger">{{ form.contact_email.errors }}</span>
                                        </div>
                                    </div>
                                    <div class="col-md-6 pl-md-1">
                                        <div class="form-group">
                                            <label>Gender</label>
                                            {{ form.gender }}
                                            <span class="text-danger">{{ form.gender.errors }}</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-8">
                                        <div class="form-group">
                                            <label>Description</label>
                                            {{ form.reporter_description }}
                                            <span class="text-danger">{{ form.description.errors }}</span>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}

                            <div class="card-footer">
                                <button type="submit" class="btn btn-fill btn-dark">Add</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- MODAL TO CROP THE IMAGE -->
    <div class="modal fade" id="modalCrop">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Crop the photo</h4>
                </div>
                <div class="modal-body">
                    <img src="" id="image" style="max-width: 100%;"/>
                </div>
                <div class="modal-footer">
                    <div class="btn-group pull-left" role="group">
                        <button type="button" class="btn btn-default js-zoom-in">
                            <i class="fas fa-search-plus"></i>
                        </button>
                        <button type="button" class="btn btn-default js-zoom-out">
                            <i class="fas fa-search-minus"></i>
                        </button>
                    </div>
                    <button type="button" class="btn btn-dark js-crop-and-upload" data-dismiss="modal">Crop</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

cases/templates/cases/cases_confirm_delete.html
<html lang="en">

<body>
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm">
    </form>
</body>
</html>