accounts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = 'accounts'
urlpatterns = [
    # path('', TemplateView.as_view(template_name='main/welcome.html'), name='home'),
    path('', UserLoginView.as_view(), name='index'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('home/', UserDashboardView.as_view(), name='dashboard'),
    path('addstaff/', AddStaffView.as_view(), name='add-staff'),
    path('viewstaff/', ListStaffView.as_view(), name='view-staff'),
    path('updatestaff/<int:pk>/', StaffUpdateView.as_view(), name='update-staff'),
    path('deletestaff/<int:pk>/', delete_staff, name='delete-staff'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('changepassword/', UserPasswordChangeView.as_view(), name='password_change'),
    path('passwordchanged/', UserPasswordChangeDoneView.as_view(), name='password_changed'),
    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(), name='activate'),
    path('profile/<int:pk>', ProfileEditView.as_view(), name='profile'),
    path('profile-info/<int:pk>', ProfileInfo.as_view(), name='profile-info'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cases/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = 'cases'

urlpatterns = [
    path('addcase/', AddCaseView.as_view(), name='add-case'),
    path('downloadcase/<int:pk>', download_case, name='download-case'),
    path('approvecase/<int:pk>', approve_view, name='approve-case'),
    path('listcases/', ListCaseView.as_view(), name='list-case'),
    path('wanted-list/', WantedCaseView.as_view(), name='wanted-list'),
    path('missing-list/', MissingCaseView.as_view(), name='missing-list'),
    path('found-list/', FoundCaseView.as_view(), name='found-list'),
    path('editcase/<int:pk>', UpdateCaseView.as_view(), name='edit-case'),
    path('deletecase/<pk>', delete_case, name='delete-case'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

detection/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = 'detection'
urlpatterns = [
    path('detectimage/', detect_image, name='detect-image'),
    path('detectwithvideo/', detect_video, name='detect-video'),
    path('detectwithwebcam/', detect_with_webcam, name='detect-webcam'),
    path('adduser/', add_staff, name='add-user'),
    path('addcitizen/', AddCitizen.as_view(), name='add-citizen'),
    path('viewcitizen/', ListCitizenView.as_view(), name='view-citizen'),
    path('deletecitizen/<int:pk>/', delete_citizen, name='delete-citizen'),
    path('updatecitizen/<int:pk>/', UpdateCitizenView.as_view(), name='update-citizen'),
    path('downloadcsvfile/<int:pk>/', csv_database_write, name='download-csv-file'),
    path('spottedcitizen/', SpottedCitizenView.as_view(), name='spotted-citizen'),
    path('citizenlocation/<int:pk>', citizen_location, name='citizen-location'),
    path('foundcitizen/<int:pk>/', found_citizen, name='found-citizen'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = 'news'
urlpatterns = [
    path('news/', NewsView.as_view(), name='list-news'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python_FaceRecognition/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('detection.urls')),
    path('', include('cases.urls')),
    path('', include('news.urls')),
    path('', include('searching.urls')),
    path('', include('feedback.urls')),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

GENDER_CHOICES = (
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Other', 'Other'),
)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    profile_image = models.ImageField(upload_to='citizens/', null=False, blank=False, default='assets/img/default-avatar.png')
    nationality = models.CharField(max_length=50, null=False, blank=False)
    citizenship_number = models.CharField(max_length=50, null=False, blank=False)
    phone_number = models.CharField(max_length=13, null=False, blank=False)
    address = models.CharField(max_length=50, null=False, blank=False)
    bio = models.TextField(max_length=500, null=False, blank=False)
    birth_date = models.DateField(null=False, blank=False)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated_at']

    def __str__(self):
        return '%s %s' % (self.user.first_name, self.user.last_name)

accounts/forms.py
import re

from django import forms
from PIL import Image
from accounts.models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm


class UserForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=100, required=True)
    username = forms.CharField(max_length=100, required=True)

    class Meta:
        model = User
        fields = ['first_name', 'last_name',
                  'username', 'email',
                  'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['class'] = 'form-control'
        self.fields['last_name'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        return user


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username']

    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['class'] = 'form-control'
        self.fields['last_name'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['class'] = 'form-control'

    def save(self, commit=True):
        user = super(UserUpdateForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        return user


class UserProfileForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height = forms.FloatField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Profile
        fields = ['profile_image', 'citizenship_number', 'nationality', 'address',
                  'bio', 'birth_date', 'gender', 'phone_number',
                  'x', 'y', 'width', 'height']

        widgets = {'address': forms.TextInput(attrs={'class': 'form-control'}),
                   'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
                   'citizenship_number': forms.NumberInput(attrs={'class': 'form-control'}),
                   'nationality': forms.TextInput(attrs={'class': 'form-control'}),
                   'bio': forms.Textarea(attrs={'class': 'form-control'}),
                   'birth_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
                   }

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')
        PHONE_NUMBER_REGEX = re.compile(r"^(([+]?\d{3})-?)?\d{7,10}$")
        if not PHONE_NUMBER_REGEX.match(phone_number):
            raise forms.ValidationError('''Phone Number format is not valid. Some examples of supported
              phone numbers are numbers are 9811111111, 08256666,
              977-9833333333, +977-9833333333, 977-08256666''')
        return phone_number

    def save(self, commit=True):
        photo = super(UserProfileForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.profile_image)
        if x and y and w and h:
            cropped_image = image.crop((x, y, w + x, h + y))
            resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
            resized_image.save(photo.profile_image.path)
        return photo


class LoginUser(forms.Form):
    username = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(required=True, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'type': 'password'}))
    new_password1 = forms.CharField(required=True, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'type': 'password'}))
    new_password2 = forms.CharField(required=True, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'type': 'password'}))

    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']

accounts/templates/accounts/account_activation_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Activate Account</title>
</head>
<body>

{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

</body>
</html>

accounts/templates/accounts/dashboard.html
{% extends "base.html" %}
{% load static %}
{% block title %} Dashboard {% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-4 col-md-6 mt-5">
            <div class="card card-bordered text-center">
                <i class="fas fa-image fa-10x"></i>
{#                <img class="card-img-top img-fluid" src="{% static  'assets/img/12345.png'%}" alt="image">#}
                <div class="card-body text-center">
                    <h5 class="title">Upload Citizen Picture</h5>

                    <button type="button" class="btn btn-dark" data-toggle="modal" data-target="#exampleModalLong">Upload Picture</button>
                    <div class="modal fade" id="exampleModalLong">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Upload Citizen Picture</h5>
                                </div>
                                <form method="post" id="id_image_detect" action="{% url 'detection:detect-image' %}" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="modal-body">
                                        <input id="inpFile" type="file" name="image"  required>
                                    </div>
                                    <div class="modal-footer">
                                        <a  type="button" class="btn btn-dark" data-dismiss="modal">Close</a>
                                        <button type="submit" class="btn btn-dark">Process</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 mt-5">
            <div class="card card-bordered text-center">
                <i class="fas fa-camera fa-10x"></i>
                <div class="card-body">
                    <h5 class="title">Upload Citizen Video</h5>
                    <button type="button" class="btn btn-dark" data-toggle="modal" data-target="#uploadVideo">Upload Video</button>
                    <div class="modal fade" id="uploadVideo">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Upload Citizen Video</h5>
                                </div>
                                <form method="post" action="{% url 'detection:detect-video' %}" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="modal-body">
                                        <input type="file" name="video" required>
                                    </div>

                                    <div class="modal-footer">
                                        <a  type="button" class="btn btn-dark" data-dismiss="modal">Close</a>
                                        <button type="submit" class="btn btn-dark">Process</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-4 col-md-6 mt-5">
            <div class="card card-bordered text-center">
                <i class="fas fa-video fa-10x"></i>
                <div class="card-body text-center">
                    <h5 class="title">Detect Using Webcam.</h5>
                    <a href="{% url 'detection:detect-webcam' %}" class="btn btn-dark">Open Webcam</a>
                </div>
            </div>
        </div>
    </div>

    <h2 class="mt-5">View Notices</h2>
    <div class="row ">
        <div class="col-lg-4 col-md-4">
            <div class="card">
                <div class="row no-gutters d-flex align-items-center justify-content-center ">
                    <div class="col-auto">
                        <img src="{% static 'assets/img/wanted.png' %}" class="img-fluid" alt="" style="height: 200px; width: 130px">
                    </div>
                    <div class="col">
                        <div class="card-block px-4">
                            <h2 class="card-title text-info">Wanted</h2>
                            <p class="card-text">View and search public Notices for wanted criminals</p>
                            <br>
                            <a href="{% url 'cases:missing-list' %}" class="alert-link mt-3">Click Here
                                <i class="tim-icons icon-double-right"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-4 col-md-4">
            <div class="card">
                <div class="row no-gutters d-flex align-items-center justify-content-center ">
                    <div class="col-auto">
                        <img src="{% static 'assets/img/missing.png' %}" class="img-fluid" alt="" style="height: 200px; width: 150px">
                    </div>
                    <div class="col">
                        <div class="card-block px-4">
                            <h2 class="card-title text-info">Missing</h2>
                            <p class="card-text">View and search public Notices for missing persons</p>
                            <br>
                            <a href="{% url 'cases:missing-list' %}" class="alert-link mt-3">Click Here
                                <i class="tim-icons icon-double-right"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-4 col-md-4">
            <div class="card">
                <div class="row no-gutters d-flex align-items-center justify-content-center ">
                    <div class="col-auto">
                        <img src="{% static 'assets/img/solved.jpg' %}" class="img-fluid" alt="" style="height: 200px; width: 150px">
                    </div>
                    <div class="col">
                        <div class="card-block px-4">
                            <h2 class="card-title text-info">Closed Cases</h2>
                            <p class="card-text">View closed cases</p>
                            <br><br>
                            <a href="{% url 'cases:found-list' %}" class="alert-link mt-3">Click Here
                                <i class="tim-icons icon-double-right"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}
{% block javascripts %}
    <script>
    $('#id_image_detect').submit(function(){
        $("#id_image_detect").append("<h4 class='text-dark'>Processing...</h4>");
    })
    </script>
{% endblock javascripts %}

accounts/templates/accounts/home.html
{% extends 'base.html' %}

{% block title %}Home Page{% endblock title %}

{% block content %}
    <h2>Home</h2>
    {% if user.is_authenticated %}
    <p>You are welcome on Home Page</p>
    <p>Your name is - {{user.first_name}} {{user.last_name}}</p>
    <p>Your email is - {{user.email}}</p>
    <br>
    <a href="{% url 'accounts:profile' user.id %}">Edit Profile</a>
    <br><br>
    <a href="{% url 'accounts:password_change' %}">Change Password</a>
    <br><br>
    <a href="{% url 'accounts:logout' %}">Logout</a>
    {% else %}
    <a href="{% url 'accounts:login' %}">Login</a>
    <br><br>
{#    <a href="{% url 'password_reset' %}">Forgot Password</a>#}
    <br><br>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
    {% endif %}
{% endblock content %}

accounts/templates/accounts/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout</title>
</head>
<body>
Logged out success !!!
    <a href="{% url 'accounts:login' %}">Login again </a>
</body>
</html>

accounts/templates/accounts/password_change_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Password Changed</title>
</head>
<body>
Password changed successfully !!
<a href="{% url 'accounts:dashboard' %}">Back to Dashboard</a>
</body>
</html>

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block javascripts %}
    <script>
        $(function () {

            /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
            $("#id_profile_image").change(function () {
                if (this.files && this.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        $("#image").attr("src", e.target.result);
                        $("#modalCrop").modal("show");
                    }
                    reader.readAsDataURL(this.files[0]);
                }
            });

            /* SCRIPTS TO HANDLE THE CROPPER BOX */
            var $image = $("#image");
            var cropBoxData;
            var canvasData;
            $("#modalCrop").on("shown.bs.modal", function () {
                $image.cropper({
                    viewMode: 1,
                    aspectRatio: 1,
                    minCropBoxWidth: 100,
                    minCropBoxHeight: 100,
                    ready: function () {
                        $image.cropper("setCanvasData", canvasData);
                        $image.cropper("setCropBoxData", cropBoxData);
                    }
                });
            }).on("hidden.bs.modal", function () {
                cropBoxData = $image.cropper("getCropBoxData");
                canvasData = $image.cropper("getCanvasData");
                $image.cropper("destroy");
            });

            $(".js-zoom-in").click(function () {
                $image.cropper("zoom", 0.1);
            });

            $(".js-zoom-out").click(function () {
                $image.cropper("zoom", -0.1);
            });

            /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
            $(".js-crop-and-upload").click(function () {
                var cropData = $image.cropper("getData");
                $("#id_x").val(cropData["x"]);
                $("#id_y").val(cropData["y"]);
                $("#id_height").val(cropData["height"]);
                $("#id_width").val(cropData["width"]);
                {#$("#formUpload").submit();#}
            });

        });
    </script>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">Update Profile</h5>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data" autocomplete="off">
                        {% csrf_token %}

                        {{ profile_form.x }}
                        {{ profile_form.y }}
                        {{ profile_form.width }}
                        {{ profile_form.height }}

                        <div class="row">
                            <div class="col-md-6 pr-md-1">
                                <div class="form-group">
                                    <label>First Name</label>
                                    {{ user_form.first_name }}
                                </div>
                            </div>
                            <span class="text-danger">{{ form.first_name.errors }}</span>

                            <div class="col-md-6 pl-md-1">
                                <div class="form-group">
                                    <label>Last Name</label>
                                    {{ user_form.last_name }}
                                </div>
                            </div>
                            <span class="text-danger">{{ form.last_name.errors }}</span>
                        </div>

                        <div class="row">
                            <div class="col-md-6 pr-md-1">
                                <div class="form-group">
                                    <label>Username</label>
                                    {{ user_form.username }}
                                </div>
                            </div>
                            <div class="col-md-6 pl-md-1">
                                <div class="form-group">
                                    <label>Email</label>
                                    {{ user_form.email }}
                                </div>
                            </div>
                        </div>
                        <span class="text-danger">{{ form.username.errors }}</span>
                        <span class="text-danger">{{ form.email.errors }}</span>

                        <div class="row">
                            <div class="col-md-6 pr-md-1">
                                <div class="form-group">
                                    <label>Address</label>
                                    {{ profile_form.address }}
                                </div>
                            </div>
                            <span class="text-danger">{{ profile_form.address.errors }}</span>
                            <div class="col-md-6 pl-md-1">
                                <div class="form-group">
                                    <label>Phone Number</label>
                                    {{ profile_form.phone_number }}
                                </div>
                                <span class="text-danger">{{ profile_form.phone_number.errors }}</span>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6 pr-md-1">
                                <div class="form-group">
                                    <label>Date of Birth</label>
                                    {{ profile_form.birth_date }}
                                </div>
                            </div>
                            <div class="col-md-6 pl-md-1">
                                <div class="form-group">
                                    <label>Gender</label><br>
                                    {{ profile_form.gender }}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6 pr-md-1">
                                <div class="form-group">
                                    <label>Citizenship Number</label>
                                    {{ profile_form.citizenship_number }}
                                </div>
                            </div>
                            <div class="col-md-6 pl-md-1">
                                <div class="form-group">
                                    <label>Nationality</label><br>
                                    {{ profile_form.nationality }}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12 pr-md-1">
                                <div class="img-holder">
                                    <label>Upload Photo</label><br>
                                    {{ profile_form.profile_image }}
                                </div>
                            </div>
                        </div><br>

                        <div class="col-md-6 pl-md-1">
                            <div class="form-group">
                                <label>Describe yourself</label>
                                {{ profile_form.bio }}
                            </div>
                        </div>

                        <div class="card-footer">
                            <button type="submit" class="btn btn-fill btn-dark">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card card-user">
                <div class="card-body">
                    <div class="author">
                        <div class="block block-one"></div>
                        <div class="block block-two"></div>
                        <div class="block block-three"></div>
                        <div class="block block-four"></div>
                        <img class="avatar" src="{{ request.user.profile.profile_image.url }}" alt="...">
                        <h5 class="title">{{ request.user.username }}</h5>
                        <p class="description">{{ request.user.email }}</p>
                        <a href="{% url 'accounts:password_change' %}"> Change password </a>
                    </div>
                    {#                <div class="card-description">#}
                    {#                    {{ request.user.profile.bio }}#}
                    {#                </div>#}
                </div>

                <div class="card-footer">
                    <div class="button-container">
                        <button href="javascript:void(0)" class="btn btn-icon btn-round btn-facebook">
                            <i class="fab fa-facebook"></i>
                        </button>
                        <button href="javascript:void(0)" class="btn btn-icon btn-round btn-twitter">
                            <i class="fab fa-twitter"></i>
                        </button>
                        <button href="javascript:void(0)" class="btn btn-icon btn-round btn-google">
                            <i class="fab fa-google-plus"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>



    <!-- MODAL TO CROP THE IMAGE -->
    <div class="modal fade" id="modalCrop">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Crop the photo</h4>
                </div>
                <div class="modal-body">
                    <img src="" id="image" style="max-width: 100%;">
                </div>
                <div class="modal-footer">
                    <div class="btn-group pull-left" role="group">
                        <button type="button" class="btn btn-default js-zoom-in">
                            <i class="fas fa-search-plus"></i>
                        </button>
                        <button type="button" class="btn btn-default js-zoom-out">
                            <i class="fas fa-search-minus"></i>
                        </button>
                    </div>
                    <button type="button" class="btn btn-dark js-crop-and-upload" data-dismiss="modal">Crop</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}