accounts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = 'accounts'
urlpatterns = [
    # path('', TemplateView.as_view(template_name='main/welcome.html'), name='home'),
    path('', UserLoginView.as_view(), name='index'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('home/', UserDashboardView.as_view(), name='dashboard'),
    path('addstaff/', AddStaffView.as_view(), name='add-staff'),
    path('viewstaff/', ListStaffView.as_view(), name='view-staff'),
    path('updatestaff/<int:pk>/', StaffUpdateView.as_view(), name='update-staff'),
    path('deletestaff/<int:pk>/', delete_staff, name='delete-staff'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('changepassword/', UserPasswordChangeView.as_view(), name='password_change'),
    path('passwordchanged/', UserPasswordChangeDoneView.as_view(), name='password_changed'),
    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(), name='activate'),
    path('profile/<int:pk>', ProfileEditView.as_view(), name='profile'),
    path('profile-info/<int:pk>', ProfileInfo.as_view(), name='profile-info'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cases/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = 'cases'

urlpatterns = [
    path('addcase/', AddCaseView.as_view(), name='add-case'),
    path('downloadcase/<int:pk>', download_case, name='download-case'),
    path('approvecase/<int:pk>', approve_view, name='approve-case'),
    path('listcases/', ListCaseView.as_view(), name='list-case'),
    path('wanted-list/', WantedCaseView.as_view(), name='wanted-list'),
    path('missing-list/', MissingCaseView.as_view(), name='missing-list'),
    path('found-list/', FoundCaseView.as_view(), name='found-list'),
    path('editcase/<int:pk>', UpdateCaseView.as_view(), name='edit-case'),
    path('deletecase/<pk>', delete_case, name='delete-case'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

detection/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = 'detection'
urlpatterns = [
    path('detectimage/', detect_image, name='detect-image'),
    path('detectwithvideo/', detect_video, name='detect-video'),
    path('detectwithwebcam/', detect_with_webcam, name='detect-webcam'),
    path('adduser/', add_staff, name='add-user'),
    path('addcitizen/', AddCitizen.as_view(), name='add-citizen'),
    path('viewcitizen/', ListCitizenView.as_view(), name='view-citizen'),
    path('deletecitizen/<int:pk>/', delete_citizen, name='delete-citizen'),
    path('updatecitizen/<int:pk>/', UpdateCitizenView.as_view(), name='update-citizen'),
    path('downloadcsvfile/<int:pk>/', csv_database_write, name='download-csv-file'),
    path('spottedcitizen/', SpottedCitizenView.as_view(), name='spotted-citizen'),
    path('citizenlocation/<int:pk>', citizen_location, name='citizen-location'),
    path('foundcitizen/<int:pk>/', found_citizen, name='found-citizen'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedback/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = 'feedback'
urlpatterns = [
    path('feedback/<int:case_pk>', FeedbackView.as_view(), name='feedback'),
    path('feedback-info/', FeedbackInfo.as_view(), name='feedback-info'),
    path('feedback-delete/<int:pk>', delete_feedback, name='feedback-delete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = 'news'
urlpatterns = [
    path('news/', NewsView.as_view(), name='list-news'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python_FaceRecognition/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('detection.urls')),
    path('', include('cases.urls')),
    path('', include('news.urls')),
    path('', include('searching.urls')),
    path('', include('feedback.urls')),

]

templates/includes/css.html
{% load static %}
<link href="{% static 'assets/css/black-dashboard.css' %}" rel="stylesheet" />
<link href="{% static 'assets/fontawesome/css/all.css' %}" rel="stylesheet">
<link href="{% static 'assets/css/nucleo-icons.css' %}" rel="stylesheet" />
<link href="{% static 'assets/css/mycss.css' %}" rel="stylesheet" />
<link href="{% static 'assets/css/sidebar.css' %}" rel="stylesheet" />
{#    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" />#}
<link href="{% static 'assets/css/cropper.min.css' %}" rel="stylesheet" />

templates/includes/footer.html
<footer class="footer">
    <div class="container-fluid">
        <ul class="nav">
        </ul>
        <div class="copyright">
            &copy; Criminal Reporting and Identification System
            <script>document.write(new Date().getFullYear())</script>
        </a>
        </div>
    </div>
</footer>

templates/includes/messages.html
{#{% for message in messages %}#}
{#<div class="container-fluid p-0">#}
{#  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >#}
{#    <button type="button" class="close" data-dismiss="alert" aria-label="Close">#}
{#      <span aria-hidden="true">&times;</span>#}
{#    </button>#}
{#    {{ message }}#}
{#  </div>#}
{#</div>#}
{#{% endfor %}#}

{% for message in messages %}
    <div class="mr-5" id="messages">
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        <strong>{{ message.tags }} ! </strong>{{message}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    </div>
{% endfor %}

templates/includes/navigation.html
<!-- Static assets -->
{% load static %}


{% if user.is_authenticated %}
    <!-- Navbar -->
    <nav class="navbar navbar-transparent navbar-expand-lg navbar-absolute navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-wrapper">
                <a class="navbar-brand" href="javascript:void(0)">Welcome {{ request.user.first_name }} {{ request.user.last_name  }}</a>
            </div>

            <div class="collapse navbar-collapse" id="navigation">
                <ul class="navbar-nav ml-auto">
                    <li class="search-bar input-group">
                        <button class="btn btn-link" id="search-button" data-toggle="modal" data-target="#searchModal"><i class="tim-icons icon-zoom-split" ></i>
                            <span class="d-lg-none d-md-block">Search</span>
                        </button>
                    </li>

                    <li class="dropdown nav-item">
                        <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                            <div class="photo">
                                {% if request.user.profile.profile_image %}
                                    <img src="{{ request.user.profile.profile_image.url }}" alt="Profile Photo" class="rounded-circle">
                                {% else %}
                                    <img src="{% static 'assets/img/default-avatar.png' %}" alt="Profile Photo">
                                {% endif %}
                            </div>
                            <b class="caret d-none d-lg-block d-xl-block"></b>
                        </a>
                        <ul class="dropdown-menu dropdown-navbar bg-dark">
                            <li class="nav-link"><a href="{% url 'accounts:profile' request.user.profile.id  %}" class="nav-item dropdown-item">Profile</a></li>
{#                            <li class="dropdown-divider"></li>#}
                            <li class="nav-link"><a href="{% url 'accounts:logout' %}" class="nav-item dropdown-item">Logout</a></li>
                        </ul>
                    </li>
                    <li class="separator d-lg-none"></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="modal modal-search fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <label for="inlineFormInputGroup"></label><input type="text" class="form-control" id="inlineFormInputGroup" placeholder="SEARCH">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <i class="tim-icons icon-simple-remove"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
{% endif %}

templates/includes/new_sidebar.html
{% load static %}
{% if user.is_authenticated %}
    <div class="page-wrapper chiller-theme toggled">
        <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
            <i class="fas fa-bars"></i>
        </a>
        <nav id="sidebar" class="sidebar-wrapper">
            <div class="sidebar-content">
                <div class="sidebar-brand">
                    <a href="{% url 'accounts:dashboard' %}">Home</a>
                    <div id="close-sidebar">
                        <i class="fas fa-times"></i>
                    </div>
                </div>
                <div class="sidebar-header">
                    <div class="user-pic">
                        {% if request.user.profile.profile_image %}
                            <img class="img-responsive img-rounded" src="{{ request.user.profile.profile_image.url }}"
                                 alt="Profile Photo">
                        {% else %}
                            <img class="img-responsive img-rounded" src="{% static 'assets/img/default-avatar.png' %}"
                                 alt="Profile Photo">
                        {% endif %}
                    </div>
                    <div class="user-info">
                        <span class="user-name"> <strong>{{ request.user.first_name }}</strong>
                            <strong>{{ request.user.last_name }}</strong>
                        </span>
                        {% if user.is_staff and user.is_superuser%}
                            <span class="user-role">Admin</span>
                        {% elif user.is_staff %}
                            <span class="user-role">Staff</span>
                        {% else %}
                            <span class="user-role">User</span>
                        {% endif %}
                    </div>
                </div>
                <!-- sidebar-header  -->
                <div class="sidebar-search">
                        <div class="input-group">
                            <div>
                                <form action="{% url 'searching:search' %}" method="GET">
                                    {% csrf_token %}
                                    <input type="text" class="form-control search-menu" placeholder="SEARCH&hellip;" name="q"
                                           value="{{ request.GET.q }}">
{#                                    <span>#}
{#                                        <i class="fa fa-search" aria-hidden="true"></i>#}
{#                                    </span>#}
                                </form>
                                </div>
                        </div>
                </div>
                <!-- sidebar-search  -->
                <div class="sidebar-menu">
                    <ul>
                        <li class="header-menu">
                            <span>General</span>
                        </li>
                        {% if user.is_staff and user.is_active %}
                            <li class="sidebar-dropdown">
                                <a href="#">
                                    <i class="tim-icons icon-single-02"></i>
                                    <span>Staff</span>
                                </a>
                                <div class="sidebar-submenu">
                                    <ul>
                                        {% if user.is_superuser %}
                                            <li>
                                                <a href="{% url 'accounts:add-staff' %}">Add Staff
                                                </a>
                                            </li>
                                        {% endif %}
                                        <li>
                                            <a href="{% url 'accounts:view-staff' %}">View Staff</a>
                                        </li>
                                    </ul>
                                </div>
                            </li>

                            <li class="sidebar-dropdown">
                                <a href="#">
                                    <i class="fa fa-users"></i>
                                    <span>Citizens</span>
                                </a>
                                <div class="sidebar-submenu">
                                    <ul>
                                        <li>
                                            <a href="{% url 'detection:add-citizen' %}">Add Citizen
                                            </a>
                                        </li>
                                        <li>
                                            <a href="{% url 'detection:view-citizen' %}">View Citizen</a>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                        {% endif %}

                        <li class="sidebar-dropdown">
                            <a href="#">
                                <i class="fas fa-file-alt "></i>
                                <span>Case</span>
                            </a>
                            <div class="sidebar-submenu">
                                <ul>
                                    <li>
                                        <a href="{% url 'cases:add-case' %}">Add Case</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'cases:list-case' %}">View Case</a>
                                    </li>
                                </ul>
                            </div>
                        </li>

                        <li class="header-menu">
                            <span>Track</span>
                        </li>
                        <li>
                            <a href="{% url 'detection:spotted-citizen' %}">
                                <i class="tim-icons icon-square-pin"></i>
                                <span>Track</span>
                            </a>
                        </li>

                        {% if user.is_superuser %}
                            <li class="header-menu">
                                <span>Messages</span>
                            </li>
                            <li class="sidebar-dropdown">
                                <a href="#">
                                    <i class="fas fa-envelope"></i>
                                    <span>Messages</span>
                                    <span class="badge badge-light">{% if feedback_count %} {{ feedback_count }} {%  else %} 0 {% endif %}</span>
                                </a>
                                <div class="sidebar-submenu">
                                    <ul>
                                        <li>
                                            <a href="{% url 'feedback:feedback-info'  %}">Feedbacks
                                            <span class="badge badge-light">{% if feedback_count %} {{ feedback_count }} {%  else %} 0 {% endif %}</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                        {% endif %}

                        <li class="header-menu">
                            <span>Profile</span>
                        </li>
                        <li class="sidebar-dropdown">
                            <a href="#">
                                <i class="fas fa-user-circle "></i>
                                <span>Profile</span>
                            </a>
                            <div class="sidebar-submenu">
                                <ul>
                                    <li>
                                        <a href="{% url 'accounts:profile' request.user.profile.id  %}">Profile</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'accounts:logout' %}">Logout</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
                <!-- sidebar-menu  -->
            </div>
        </nav>
    </div>
{% endif %}

templates/includes/scripts-sidebar.html
  <script>
    $(document).ready(function() {
      $().ready(function() {
        $sidebar = $('.sidebar');
        $navbar = $('.navbar');
        $main_panel = $('.main-panel');

        $full_page = $('.full-page');

        $sidebar_responsive = $('body > .navbar-collapse');
        sidebar_mini_active = true;
        white_color = false;

        window_width = $(window).width();

        fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();



        $('.fixed-plugin a').click(function(event) {
          if ($(this).hasClass('switch-trigger')) {
            if (event.stopPropagation) {
              event.stopPropagation();
            } else if (window.event) {
              window.event.cancelBubble = true;
            }
          }
        });

        $('.fixed-plugin .background-color span').click(function() {
          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data', new_color);
          }

          if ($main_panel.length != 0) {
            $main_panel.attr('data', new_color);
          }

          if ($full_page.length != 0) {
            $full_page.attr('filter-color', new_color);
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.attr('data', new_color);
          }
        });

        $('.switch-sidebar-mini input').on("switchChange.bootstrapSwitch", function() {
          var $btn = $(this);

          if (sidebar_mini_active == true) {
            $('body').removeClass('sidebar-mini');
            sidebar_mini_active = false;
            blackDashboard.showSidebarMessage('Sidebar mini deactivated...');
          } else {
            $('body').addClass('sidebar-mini');
            sidebar_mini_active = true;
            blackDashboard.showSidebarMessage('Sidebar mini activated...');
          }

          // we simulate the window Resize so the charts will get updated in realtime.
          var simulateWindowResize = setInterval(function() {
            window.dispatchEvent(new Event('resize'));
          }, 180);

          // we stop the simulation of Window Resize after the animations are completed
          setTimeout(function() {
            clearInterval(simulateWindowResize);
          }, 1000);
        });

        $('.switch-change-color input').on("switchChange.bootstrapSwitch", function() {
          var $btn = $(this);

          if (white_color == true) {

            $('body').addClass('change-background');
            setTimeout(function() {
              $('body').removeClass('change-background');
              $('body').removeClass('white-content');
            }, 900);
            white_color = false;
          } else {

            $('body').addClass('change-background');
            setTimeout(function() {
              $('body').removeClass('change-background');
              $('body').addClass('white-content');
            }, 900);

            white_color = true;
          }


        });

        $('.light-badge').click(function() {
          $('body').addClass('white-content');
        });

        $('.dark-badge').click(function() {
          $('body').removeClass('white-content');
        });
      });
    });
  </script>

templates/includes/scripts.html
<!-- Static assets -->
{% load static %}

<!--   Core JS Files   -->
<script src="{% static 'assets/js/core/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/cropper.min.js' %}"></script>

<script src="{% static 'assets/js/core/popper.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>

{#<!-- Chart JS -->#}
{#<script src="{% static 'assets/js/plugins/chartjs.min.js' %}"></script>#}

{#<!--  Notifications Plugin    -->#}
<script src="{% static 'assets/js/plugins/bootstrap-notify.js' %}"></script>

{#<!-- Control Center for Black Dashboard: parallax effects, scripts for the example pages etc -->#}
<script src="{% static 'assets/js/black-dashboard.min.js' %}"></script><!-- Black Dashboard DEMO methods, don't include it in your project! -->
<script src="{% static 'assets/demo/demo.js' %}"></script>
<script src="{% static 'assets/js/sidebar.js' %}"></script>
<script src="{% static 'assets/js/progress.js' %}"></script>

templates/includes/sidebar.html
{% if user.is_authenticated %}
    <div class="sidebar">
        <div class="sidebar-wrapper bg-dark">

            <ul class="nav">
                <li class="active ">
                    <a href="{% url 'accounts:dashboard' %}">
                        <i class="tim-icons icon-chart-pie-36"></i>
                        <p>Home</p>
                    </a>
                </li>
                <li>
                    {% if user.is_superuser and user.is_active %}
                        <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                            <i class="tim-icons icon-single-02"></i>
                            <p>Staff</p>
                        </a>
                        <ul class="collapse list-unstyled" id="pageSubmenu">
                            <li>
                                <a href="{% url 'accounts:register' %}">
                                    <i class="fa fa-user-plus"></i>
                                    <p>Add Staff</p>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'accounts:view-staff' %}">
                                    <i class="tim-icons icon-zoom-split"></i>
                                    <p>View Staff</p>
                                </a>

                            </li>
                        </ul>


                        {#                {% if user.is_staff and user.is_active and user.is_superuser %}#}
{#                        <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">#}
{#                            <i class="tim-icons icon-single-02"></i>#}
{#                            <p>Staff</p>#}
{#                        </a>#}
{#                        <ul class="collapse list-unstyled" id="pageSubmenu">#}
{#                            <li>#}
{#                                <a href="{% url 'accounts:view-staff' %}">#}
{#                                    <i class="tim-icons icon-zoom-split"></i>#}
{#                                    <p>View Staff</p>#}
{#                                </a>#}
{#                            </li>#}
{#                        </ul>#}

                        <li>
                            <a href="#pageSubmenu2" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                                <i class="fa fa-users" aria-hidden="true"></i>
                                <p>Citizen</p>
                            </a>
                            <ul class="collapse list-unstyled" id="pageSubmenu2">

                                <li>
                                    <a href="{% url 'detection:add-citizen' %}">
                                        <i class="fa fa-user-plus"></i>
                                        <p>Add Citizen</p>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'detection:view-citizen' %}">
                                        <i class="tim-icons icon-zoom-split"></i>
                                        <p>View Citizens</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    {% endif %}

                <li>
                    <a href="#pageSubmenu3" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="fas fa-file" aria-hidden="true"></i>
                        <p>Cases</p>
                    </a>
                    <ul class="collapse list-unstyled" id="pageSubmenu3">
                        <li>
                            <a href="{% url 'cases:add-case' %}">
                                <i class="fa fa-user-plus"></i>
                                <p>Add Case</p>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'cases:list-case' %}">
                                <i class="tim-icons icon-zoom-split"></i>
                                <p>View Case</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li>
                    <a href="{% url 'detection:spotted-citizen' %}" >
                        <i class="tim-icons icon-square-pin"></i>
                        <p>Track</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'accounts:logout' %}" >
                        <i class="tim-icons icon-user-run"></i>
                        <p>Logout</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>
{% endif %}