detection/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = 'detection'
urlpatterns = [
    path('detectimage/', detect_image, name='detect-image'),
    path('detectwithvideo/', detect_video, name='detect-video'),
    path('detectwithwebcam/', detect_with_webcam, name='detect-webcam'),
    path('adduser/', add_staff, name='add-user'),
    path('addcitizen/', AddCitizen.as_view(), name='add-citizen'),
    path('viewcitizen/', ListCitizenView.as_view(), name='view-citizen'),
    path('deletecitizen/<int:pk>/', delete_citizen, name='delete-citizen'),
    path('updatecitizen/<int:pk>/', UpdateCitizenView.as_view(), name='update-citizen'),
    path('downloadcsvfile/<int:pk>/', csv_database_write, name='download-csv-file'),
    path('spottedcitizen/', SpottedCitizenView.as_view(), name='spotted-citizen'),
    path('citizenlocation/<int:pk>', citizen_location, name='citizen-location'),
    path('foundcitizen/<int:pk>/', found_citizen, name='found-citizen'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = 'news'
urlpatterns = [
    path('news/', NewsView.as_view(), name='list-news'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python_FaceRecognition/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('detection.urls')),
    path('', include('cases.urls')),
    path('', include('news.urls')),
    path('', include('searching.urls')),
    path('', include('feedback.urls')),

]

detection/models.py
from django.db import models
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.db.models import Q
private_storage = FileSystemStorage(location=settings.PRIVATE_STORAGE_ROOT)


GENDER_CHOICES = (
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Other', 'Other'),
)

STATUS_CHOICES = (
    ('Free', 'Free'),
    ('Wanted', 'Wanted'),
    ('Missing', 'Missing'),
    ('Found', 'Found'),
)


class CitizenProfileQueryset(models.QuerySet):
    def search(self, query=None):
        qs = self
        if query is not None:
            or_lookup = (Q(first_name__icontains=query) | Q(last_name__icontains=query) | Q(
                status__iexact=query) | Q(gender__iexact=query))
            qs = qs.filter(or_lookup).distinct()
        return qs


class CitizenProfileManager(models.Manager):
    def get_queryset(self):
        return CitizenProfileQueryset(self.model, using=self._db)

    def search(self, query=None):
        return self.get_queryset().search(query=query)


class CitizenProfile(models.Model):
    first_name = models.CharField(max_length=30, blank=False, null=False)
    last_name = models.CharField(max_length=30, blank=False, null=False)
    birth_date = models.DateField()
    address = models.CharField(max_length=100, blank=False, null=False)
    phone_number = models.CharField(max_length=13, blank=False, null=False)
    nationality = models.CharField(max_length=50, blank=False, null=False)
    citizenship_number = models.CharField(max_length=20, blank=False, null=False)
    citizen_image = models.ImageField(upload_to='citizens/', null=False, blank=False)
    bio = models.TextField(max_length=255, null=False, blank=False)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    status = models.CharField(max_length=30, choices=STATUS_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated_at']

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    objects = CitizenProfileManager()


class SpottedCitizen(models.Model):
    first_name = models.CharField(max_length=30, blank=False, null=False)
    last_name = models.CharField(max_length=30, blank=False, null=False)
    location = models.CharField(max_length=50, blank=False, null=True)
    date_of_spotted = models.DateTimeField(blank=False, null=True)
    image = models.ImageField(upload_to='spotted/', null=False, blank=False)
    status = models.CharField(max_length=30, choices=STATUS_CHOICES)
    description = models.TextField(max_length=255, null=False, blank=False)
    latitude = models.FloatField()
    longitude = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated_at']

    def __str__(self):
        return self.first_name + ' ' + self.last_name

detection/forms.py
from django import forms
from .models import *
from PIL import Image


class CitizenForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = CitizenProfile
        fields = ('first_name', 'last_name', 'birth_date', 'gender', 'address', 'phone_number', 'nationality', 'citizenship_number',
                  'bio', 'citizen_image', 'status', 'x', 'y', 'width', 'height')
        widgets = {'first_name': forms.TextInput(attrs={'class': 'form-control'}),
                   'last_name': forms.TextInput(attrs={'class': 'form-control'}),
                   'birth_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
                   'address': forms.TextInput(attrs={'class': 'form-control'}),
                   'phone_number': forms.NumberInput(attrs={'class': 'form-control'}),
                   'nationality': forms.TextInput(attrs={'class': 'form-control'}),
                   'citizenship_number': forms.NumberInput(attrs={'class': 'form-control'}),
                   # 'citizen_image': forms.FileInput(attrs={'accept': 'image/*'}),
                   'bio': forms.Textarea(attrs={'class': 'form-control'}),
                   }

    def save(self, commit=True):
        photo = super(CitizenForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.citizen_image)
        cropped_image = image.crop((x, y, w + x, h + y))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        resized_image.save(photo.citizen_image.path)

        return photo

detection/views.py
import csv
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
import face_recognition
from PIL import Image, ImageDraw
import numpy as np
import cv2
from django.core.files.storage import FileSystemStorage
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView
from django.utils.decorators import method_decorator
from cases.models import CasesModel
from .forms import CitizenForm
from .models import CitizenProfile, SpottedCitizen
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


@login_required
# @method_decorator(login_required, name='dispatch')
def add_staff(request):
    return render(request, 'accounts/register.html')


@method_decorator(login_required, name='dispatch')
class AddCitizen(CreateView):
    template_name = 'detection/add_citizen.html'
    form_class = CitizenForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        # import pdb;pdb.set_trace()
        if form.is_valid():
            form.save()
            messages.success(request, 'Citizen saved successfully')
            return redirect('detection:view-citizen')

        messages.error(request, 'Please check your credentials again')
        return render(request, self.template_name, {'form': form})


@method_decorator(login_required, name='dispatch')
class ListCitizenView(ListView):
    template_name = 'detection/view_citizen.html'
    model = CitizenProfile
    context_object_name = 'citizens'


@login_required
def delete_citizen(request, pk):
    try:
        citizen = CitizenProfile.objects.get(pk=pk)
    except CitizenProfile.DoesNotExist:
        messages.error(request, "Citizen not found")
        return redirect('detection:view-citizen')
    citizen.delete()
    messages.success(request, "Citizen deleted successfully")
    return redirect('detection:view-citizen')


@method_decorator(login_required, name='dispatch')
class UpdateCitizenView(UpdateView):
    model = CitizenProfile
    form_class = CitizenForm
    template_name = 'detection/update_citizen.html'
    success_url = reverse_lazy('detection:view-citizen')

    # def post(self, request, *args, **kwargs):
    #     form = self.form_class(request.POST, request.FILES)
    #     # import pdb;pdb.set_trace()
    #     if form.is_valid():
    #         form.save()
    #         messages.success(request, 'Citizen Updated successfully')
    #         return redirect('detection:view-citizen')
    #
    #     messages.error(request, 'Please check your credentials again')
    #     return render(request, self.template_name, {'form': form})


@method_decorator(login_required, name='dispatch')
class SpottedCitizenView(ListView):
    model = SpottedCitizen
    template_name = 'detection/spotted_citizen.html'
    context_object_name = 'citizens'
    paginate_by = 5


@login_required
def citizen_location(request, pk):
    wanted_citizen = SpottedCitizen.objects.filter(pk=pk)
    context = {
        "citizen_location": wanted_citizen
    }
    return render(request, 'detection/location.html', context)


@login_required
def found_citizen(request, pk):
    free = SpottedCitizen.objects.filter(pk=pk)
    freecitizen = SpottedCitizen.objects.filter(id=free.get().id).update(status='Found')
    if freecitizen:
        citizen = SpottedCitizen.objects.filter(pk=pk)
        free = CasesModel.objects.filter(id=citizen.get().id).update(status='Found')
        if free:
            messages.success(request, messages.INFO, "Citizen updated to found, congratulations")
        else:
            messages.error(request, "Failed to update citizen status")
    return redirect('detection:spotted-citizen')


@login_required
def csv_database_write(request, pk):
    # Get all data from UserDetail Database Table
    try:
        citizen = CitizenProfile.objects.get(pk=pk)
    except CitizenProfile.DoesNotExist:
        messages.error(request, "Citizen not found")
        return redirect('detection:view-citizen')

    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="Details.csv"'

    writer = csv.writer(response)
    writer.writerow(['first_name', 'last_name', 'address', 'phone_number',
                     'nationality', 'citizenship_number',
                     'bio', 'citizenship_image', 'status', 'birth_date'])

    writer.writerow([citizen.first_name, citizen.last_name, citizen.address, citizen.phone_number,
                     citizen.nationality, citizen.citizenship_number, citizen.bio,
                     citizen.citizen_image, citizen.status, citizen.birth_date])

    return response


@login_required
# @method_decorator(login_required, name='dispatch')
def detect_image(request):
    if request.method == 'POST' and request.FILES['image']:
        myfile = request.FILES['image']
        # fs = FileSystemStorage(base_url='media/uploads')
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)

        # img_upload = FileSystemStorage(location='media/uploads')
        # img_save = img_upload.save(myfile.name, myfile)
        # img_file_url = img_upload.url(img_save)

    images = []
    encodings = []
    names = []
    files = []
    case_id = []

    cases = CasesModel.objects.all()
    for crime in cases:
        images.append(crime.case_first_name + '_image')
        encodings.append(crime.case_first_name + '_face_encoding')
        files.append(crime.image)
        names.append(crime.case_first_name + ' ' + crime.case_last_name)
        case_id.append(crime.id)

    for i in range(0, len(images)):
        try:
            images[i] = face_recognition.load_image_file(files[i])
            encodings[i] = face_recognition.face_encodings(images[i])[0]
        except IndexError:
            messages.INFO(request, 'Not able to locate any faces.')
            return redirect('accounts:dashboard')

    # Create arrays of known face encodings and their names
    known_face_encodings = encodings
    known_face_names = names
    c_id = case_id

    # Load an image with an unknown face
    unknown_image = face_recognition.load_image_file(uploaded_file_url[1:])

    # Find all the faces and face encodings in the unknown image
    face_locations = face_recognition.face_locations(unknown_image)
    face_encodings = face_recognition.face_encodings(unknown_image, face_locations)

    # Convert the image to a PIL-format image so that we can draw on top of it with the Pillow library
    pil_image = Image.fromarray(unknown_image)
    # Create a Pillow ImageDraw Draw instance to draw with
    draw = ImageDraw.Draw(pil_image)

    # Loop through each face found in the unknown image
    for (top, right, bottom, left), face_encoding in zip(face_locations, face_encodings):
        # See if the face is a match for the known face(s)
        matches = face_recognition.compare_faces(known_face_encodings, face_encoding)

        name = "Unknown"
        status = "Unknown"

        # If a match was found in known_face_encodings, just use the first one.
        # if True in matches:
        #     first_match_index = matches.index(True)
        #     name = known_face_names[first_match_index]

        # Or instead, use the known face with the smallest distance to the new face
        face_distances = face_recognition.face_distance(known_face_encodings, face_encoding)
        try:
            best_match_index = np.argmin(face_distances)
        except ValueError:
            messages.INFO(request, 'No image found')
            return redirect('accounts:dashboard')
        if matches[best_match_index]:
            ca_id = c_id[best_match_index]
            person = CasesModel.objects.filter(id=ca_id)
            name = known_face_names[best_match_index]
            status = 'status: ' + person.get().status
            print('found')

        # Draw a box around the face using the Pillow module
        draw.rectangle(((left, top), (right, bottom)), outline=(0, 0, 255))

        # Draw a label with a name below the face
        text_width, text_height = draw.textsize(name)
        draw.rectangle(((left, bottom - text_height - 10), (right, bottom + 15)), fill=(0, 0, 255), outline=(0, 0, 255))
        draw.text((left + 6, bottom - text_height - 5), name, fill=(255, 255, 255, 255))
        draw.text((left + 6, bottom - text_height + 10), status, fill=(255, 255, 255, 255))

    if draw:
        # Remove the drawing library from memory as per the Pillow docs
        del draw

        # Display the resulting image
        pil_image.show()
        return redirect('cases:list-case')

        # You can also save a copy of the new image to disk if you want by uncommenting this line
        # pil_image.save("image_with_boxes.jpg")

    else:
        print('try again')


@login_required
def detect_video(request):
    # upload image
    myfile = []

    if request.method == 'POST' and request.FILES['video']:
        myfile = request.FILES['video']
        print("video poseted")
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)

        # Create an output movie file (make sure resolution/frame rate matches input video!)
        fourcc = cv2.VideoWriter_fourcc(*'XVID')
        output_movie = cv2.VideoWriter('output.avi', fourcc, 29.97, (640, 360))

    images = []
    encodings = []
    names = []
    files = []
    case_id = []
    frame_number = 0

    citizen = CasesModel.objects.all()
    for crime in citizen:
        images.append(crime.case_first_name + '_video')
        encodings.append(crime.case_first_name + '_face_encoding')

detection/templates/detection/add_citizen.html
{% extends 'base.html' %}

{% block javascripts %}
    <script>
        $(function () {

            /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
            $("#id_citizen_image").change(function () {
                if (this.files && this.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        $("#image").attr("src", e.target.result);
                        $("#modalCrop").modal("show");
                    }
                    reader.readAsDataURL(this.files[0]);
                }
            });

            /* SCRIPTS TO HANDLE THE CROPPER BOX */
            var $image = $("#image");
            var cropBoxData;
            var canvasData;
            $("#modalCrop").on("shown.bs.modal", function () {
                $image.cropper({
                    viewMode: 1,
                    aspectRatio: 1/1,
                    minCropBoxWidth: 200,
                    minCropBoxHeight: 200,
                    ready: function () {
                        $image.cropper("setCanvasData", canvasData);
                        $image.cropper("setCropBoxData", cropBoxData);
                    }
                });
            }).on("hidden.bs.modal", function () {
                cropBoxData = $image.cropper("getCropBoxData");
                canvasData = $image.cropper("getCanvasData");
                $image.cropper("destroy");
            });

            $(".js-zoom-in").click(function () {
                $image.cropper("zoom", 0.1);
            });

            $(".js-zoom-out").click(function () {
                $image.cropper("zoom", -0.1);
            });

            /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
            $(".js-crop-and-upload").click(function () {
                var cropData = $image.cropper("getData");
                $("#id_x").val(cropData["x"]);
                $("#id_y").val(cropData["y"]);
                $("#id_height").val(cropData["height"]);
                $("#id_width").val(cropData["width"]);
                {#$("#formUpload").submit();#}
            });

        });
    </script>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">Add Citizen</h5>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data" id="formUpload">
                        {% csrf_token %}

                        {{ form.x }}
                        {{ form.y }}
                        {{ form.width }}
                        {{ form.height }}

                        <div class="row">
                            <div class="col-md-6 pr-md-1">
                                <div class="form-group">
                                    <label>First Name</label>
                                    {{ form.first_name }}
                                </div>
                            </div>
                            <div class="col-md-6 pl-md-1">
                                <div class="form-group">
                                    <label>Last Name</label>
                                    {{ form.last_name }}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6 pr-md-1">
                                <div class="form-group">
                                    <label>Address</label>
                                    {{ form.address }}
                                </div>
                            </div>
                            <div class="col-md-6 pl-md-1">
                                <div class="form-group">
                                    <label>Phone Number</label>
                                    {{ form.phone_number }}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6 pr-md-1">
                                <div class="form-group">
                                    <label>Nationality</label>
                                    {{ form.nationality }}
                                </div>
                            </div>
                            <div class="col-md-6 pl-md-1">
                                <div class="form-group">
                                    <label>Citizenship Number</label>
                                    {{ form.citizenship_number }}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4 pr-md-1">
                                <div class="form-group">
                                    <label>Date of Birth</label><br>
                                    {{ form.birth_date }}
                                </div>
                            </div>
                            <div class="col-md-2 pr-md-1">
                                <div class="form-group">
                                    <label>Gender</label><br>
                                    {{ form.gender }}
                                </div>
                            </div>
                            <div class="col-md-4 pr-md-1">
                                <div class="form-group">
                                    <label>Status</label><br>
                                    {{ form.status }}
                                </div>
                            </div>
                        </div><br>

                        <div class="row">
                            <div class="col-md-4 pr-md-1">
                                <div class="img-holder">
                                    <label>Upload Photo</label><br>
                                    {{ form.citizen_image }}
                                </div>
                            </div>
                        </div><br>

                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label>About Me</label>
                                    {{ form.bio }}
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-fill btn-dark">Add</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

    <!-- MODAL TO CROP THE IMAGE -->
    <div class="modal fade" id="modalCrop">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Crop the photo</h4>
                </div>
                <div class="modal-body">
                    <img src="" id="image" style="max-width: 100%;">
                </div>
                <div class="modal-footer">
                    <div class="btn-group pull-left" role="group">
                        <button type="button" class="btn btn-default js-zoom-in">
                            <i class="fas fa-search-plus"></i>
                        </button>
                        <button type="button" class="btn btn-default js-zoom-out">
                            <i class="fas fa-search-minus"></i>
                        </button>
                    </div>
                    <button type="button" class="btn btn-dark js-crop-and-upload" data-dismiss="modal">Crop</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

detection/templates/detection/detection_confirm_delete.html
<html lang="en">

<body>
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm">
    </form>
</body>
</html>

detection/templates/detection/location.html
{% extends 'base.html' %}
{% block stylesheets %}
<style type="text/css">

    #map { width: 800px;
        height: 400px;
        margin-left: 10%;
    }

</style>
{% endblock %}
{% block content %}


<script type="text/javascript" src="https://maps.google.com/maps/api/js?key=AIzaSyDPnYHDjWlBThNYSM4aiGDObNNQV7jEqVk"></script>

<script type="text/javascript">

    x = navigator.geolocation;

    x.getCurrentPosition(success, failure);

    function success(position)
    {
        var myLat = position.coords.latitude;
        var myLong = position.coords.longitude;

        var coords = new google.maps.LatLng(myLat, myLong);

        var mapOptions = {

            zoom: 9,
            center: coords,
            mapTypeId: google.maps.MapTypeId.ROADMAP

        }

        var map = new google.maps.Map(document.getElementById("map"), mapOptions);

        var marker = new google.maps.Marker({map:map, position: coords});

    }

    function failure()
    {

    }

</script>

<div id="map"> </div>

{% endblock %}